version: '3'

services:
  nodejs:
    #fill out the configuration here
    build:
      context: .
      dockerfile: Dockerfile
    image: ybar_website
    container_name: ybar_website
    restart: unless-stopped
    networks:
      - app-network
  
  #the nginx configuration is given below
  #the website will run on localhost:80 
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      #fill out your absolute path to your folder here
      device: /c/Users/bar89/cmsc338T-web-template/
      o: bind

networks:
  app-network:
    driver: bridge 
